"use client";

import { useState } from "react";
import { FileDown, FileJson, Loader2 } from "lucide-react";
import jsPDF from "jspdf";
import type { ScanResult } from "@/types";

interface PdfExportProps {
  scanResult: ScanResult;
}

export default function PdfExport({ scanResult }: PdfExportProps) {
  const [generating, setGenerating] = useState(false);

  const generatePdf = async () => {
    setGenerating(true);

    try {
      const doc = new jsPDF();
      const r = scanResult;
      let y = 20;

      // Title
      doc.setFontSize(24);
      doc.setTextColor(6, 182, 212);
      doc.text("TraceGuard", 20, y);
      doc.setFontSize(12);
      doc.setTextColor(150, 150, 150);
      doc.text("OSINT Exposure Report", 80, y);
      y += 15;

      // Line
      doc.setDrawColor(6, 182, 212);
      doc.setLineWidth(0.5);
      doc.line(20, y, 190, y);
      y += 15;

      // Risk Score
      doc.setFontSize(14);
      doc.setTextColor(255, 255, 255);
      const scoreColor = r.riskScore.category === "CRITICAL" ? [220, 38, 38] :
                         r.riskScore.category === "HIGH" ? [239, 68, 68] :
                         r.riskScore.category === "MODERATE" ? [245, 158, 11] :
                         [16, 185, 129];
      doc.setTextColor(scoreColor[0], scoreColor[1], scoreColor[2]);
      doc.text(`Risk Score: ${r.riskScore.score}/100 — ${r.riskScore.category}`, 20, y);
      y += 12;

      // Score methodology
      doc.setFontSize(8);
      doc.setTextColor(120, 120, 120);
      doc.text("Formula: 0.35×Breach + 0.25×Data + 0.20×Mentions + 0.10×Correlation + 0.10×Confidence", 20, y);
      y += 12;

      // Breaches
      doc.setFontSize(12);
      doc.setTextColor(239, 68, 68);
      doc.text(`Data Breaches (${r.breaches.length} found)`, 20, y);
      y += 8;
      doc.setFontSize(9);
      doc.setTextColor(80, 80, 80);
      r.breaches.forEach(b => {
        doc.text(`• ${b.name} (${new Date(b.date).getFullYear()}) — ${b.severity.toUpperCase()} — ${b.dataClasses.join(", ")}`, 24, y);
        y += 6;
      });
      y += 6;

      // Social Profiles
      doc.setFontSize(12);
      doc.setTextColor(6, 182, 212);
      doc.text(`Social Profiles (${r.socialProfiles.length} found)`, 20, y);
      y += 8;
      doc.setFontSize(9);
      doc.setTextColor(80, 80, 80);
      r.socialProfiles.forEach(p => {
        doc.text(`• ${p.platform}: ${p.username} (${p.confidence}% confidence) — ${p.profileUrl}`, 24, y);
        y += 6;
      });
      y += 6;

      // Threat Summary
      doc.setFontSize(12);
      doc.setTextColor(245, 158, 11);
      doc.text("AI Threat Analysis", 20, y);
      y += 8;
      doc.setFontSize(9);
      doc.setTextColor(80, 80, 80);
      const summaryLines = doc.splitTextToSize(r.threatSummary.summary, 160);
      doc.text(summaryLines, 24, y);
      y += summaryLines.length * 5 + 4;

      // Attack Vectors
      r.threatSummary.attackVectors.forEach(v => {
        doc.text(`• ${v.name}: ${v.probability} probability`, 24, y);
        y += 6;
      });
      y += 6;

      // Remediation
      if (y > 240) { doc.addPage(); y = 20; }
      doc.setFontSize(12);
      doc.setTextColor(16, 185, 129);
      doc.text("Remediation Steps", 20, y);
      y += 8;
      doc.setFontSize(9);
      doc.setTextColor(80, 80, 80);
      r.remediationSteps.forEach(step => {
        doc.text(`Step ${step.step}: ${step.title}`, 24, y);
        y += 5;
        const descLines = doc.splitTextToSize(step.description, 155);
        doc.setTextColor(120, 120, 120);
        doc.text(descLines, 28, y);
        y += descLines.length * 4 + 4;
        doc.setTextColor(80, 80, 80);
      });

      // Footer
      y = 280;
      doc.setFontSize(7);
      doc.setTextColor(150, 150, 150);
      doc.text(`Generated by TraceGuard — ${new Date().toISOString()} — Zero Storage Mode`, 20, y);

      doc.save(`traceguard-report-${r.id}.pdf`);
    } catch (err) {
      console.error("PDF generation error:", err);
    } finally {
      setGenerating(false);
    }
  };

  const downloadJson = () => {
    const blob = new Blob([JSON.stringify(scanResult, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `traceguard-report-${scanResult.id}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex items-center gap-3">
      <button
        onClick={generatePdf}
        disabled={generating}
        className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-cyber-cyan to-cyber-green text-navy-950 font-semibold text-sm hover:shadow-lg hover:shadow-cyber-cyan/25 transition-all disabled:opacity-50"
      >
        {generating ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : (
          <FileDown className="w-4 h-4" />
        )}
        Download PDF Report
      </button>
      <button
        onClick={downloadJson}
        className="flex items-center gap-2 px-4 py-2.5 rounded-xl border border-white/10 text-sm text-gray-400 hover:text-white hover:border-white/20 transition-all"
      >
        <FileJson className="w-4 h-4" />
        JSON
      </button>
    </div>
  );
}
